(ns bootleg.namespaces)

(def namespaces
  {'Math {
          'abs #(Math/abs %1)
          'acos #(Math/acos %1)
          'asin #(Math/asin %1)
          'atan #(Math/atan %1)
          'atan2 #(Math/atan2 %1 %2)
          'cbrt #(Math/cbrt %1)
          'ceil #(Math/ceil %1)
          'copySign #(Math/copySign %1 %2)
          'cos #(Math/cos %1)
          'cosh #(Math/cosh %1)
          'exp #(Math/exp %1)
          'expm1 #(Math/expm1 %1)
          'floor #(Math/floor %1)
          'floorDiv #(Math/floorDiv %1 %2)
          'floorMod #(Math/floorMod %1 %2)
          'log #(Math/log %1)
          'log10 #(Math/log10 %1)
          'pow #(Math/pow %1 %2)
          'random #(Math/random)
          'rint #(Math/rint %1)
          'round #(Math/round %1)
          'signum #(Math/signum %1)
          'sin #(Math/sin %1)
          'sinh #(Math/sinh %1)
          'sqrt #(Math/sqrt %1)
          'tan #(Math/tan %1)
          'tanh #(Math/tanh %1)
          'toDegrees #(Math/toDegrees %1)
          'toIntExact #(Math/toIntExact %1)
          'toRadians #(Math/toRadians %1)
          'E Math/E
          'PI Math/PI
          }})
