# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  jvm:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-lein-2.9.0
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc zlib1g-dev make
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-22.0.0.2 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-linux-amd64-22.0.0.2.tar.gz
              tar xzf graalvm-ce-java11-linux-amd64-22.0.0.2.tar.gz
            fi
      - run:
          name: Run JVM tests
          command: |
            make tests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Create uberjar
          command: |
            mkdir -p /tmp/release
            make clean uberjar
            VERSION=$(cat .meta/VERSION)
            cp target/uberjar/bootleg-$VERSION-standalone.jar /tmp/release
      - store_artifacts:
          path: /tmp/release
          destination: release

  linux:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.0
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      GRAALVM_HOME: /home/circleci/graalvm-ce-java11-22.0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Clojure
          command: |
            wget https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc zlib1g-dev make
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-22.0.0.2 ]; then
              curl -O -sL https://github.com/oracle/graal/releases/download/vm-22.0.0.2/graalvm-ce-java11-linux-amd64-22.0.0.2.tar.gz
              tar xzf graalvm-ce-java11-linux-amd64-22.0.0.2.tar.gz
            fi
            graalvm-ce-java11-22.0.0.2/bin/gu install native-image
      - run:
          name: Build binary
          command: |
            make copy-libs-to-resource clean all package-linux GRAALVM=$GRAALVM_HOME
          no_output_timeout: 40m
      - run:
          name: Copy artifacts
          command: |
            cp *.tgz /tmp/release
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java11-22.0.0.2
          key: linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: /tmp/release
          destination: release
  mac:
    macos:
      xcode: "12.0.0"
    environment:
      GRAALVM_HOME: /Users/distiller/graalvm-ce-java11-22.0.0.2/Contents/Home
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Clojure
          command: |
            .circleci/script/install-clojure /usr/local
      - run:
          name: Install Leiningen
          command: |
            .circleci/script/install-leiningen
      - run:
          name: Download GraalVM
          command: |
            cd ~
            ls -la
            if ! [ -d graalvm-ce-java11-22.0.0.2 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-darwin-amd64-22.0.0.2.tar.gz
              tar xzf graalvm-ce-java11-darwin-amd64-22.0.0.2.tar.gz
            fi
            $GRAALVM_HOME/bin/gu install native-image
      - run:
          name: Run JVM tests
          command: |
            make tests GRAALVM=$GRAALVM_HOME
      - run:
          name: Build binary
          command: |
            make copy-libs-to-resource clean build/bootleg package-macos GRAALVM=$GRAALVM_HOME
          no_output_timeout: 40m
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java11-22.0.0.2
          key: mac-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: /tmp/release
          destination: release

workflows:
  version: 2
  ci:
    jobs:
      - jvm:
          filters:
            branches:
              only: master
      - mac:
          filters:
            branches:
              only: master

      # build on free circleci account runs out of ram
      # Error: Image build request failed with exit status 137
      # - linux
